{
 "title": "Foptimum",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Download Speed (MB/S)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "speedtest_download / 100000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Upload Speed (MB/S)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "speedtest_upload / 100000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "speedtest_latency", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Failed Pings",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "increase(ping_fails_total[1m])", "legendFormat": "Fail" }
   ]
  }
 ]
}